session_name: Command Center
windows:
- window_name: dev window
  layout: tiled
  panes:
    - shell_command:
        - cd ftp
        - cls
        - su csc446 -c 'python3 ftp_server1.py'
    - shell_command:
        - cd ftp
        - cls
        - su csc446 -c 'python3 ftp_server2.py'
    - shell_command:
        - cd ftp
        - cls
        - su csc446 -c 'python3 conversation_engine.py'
    - shell_command:
        - cd gotty
        - cls
        - su csc446 -c './start.sh'
    - shell_command:
        - cd timing
        - cls
        - su csc446 -c './start.sh'
    - shell_command:
        - export PATH="$PATH:."
        - cls
        - ./information.sh
        - bash