session_name: Command Center
windows:
- window_name: dev window
  layout: tiled
  panes:
    - shell_command:
        - cd ftp
        - clear
        - 'python3 ftp_server1.py'
    - shell_command:
        - cd ftp
        - clear
        - 'python3 ftp_server2.py'
    - shell_command:
        - cd ftp
        - clear
        - 'python3 conversation_engine.py'
    - shell_command:
        - cd gotty
        - clear
        - './start.sh'
    - shell_command:
        - cd timing
        - clear
        - './start.sh'
    - shell_command:
        - export PATH="$PATH:."
        - clear
        - ./information.sh
        - bash