session_name: Command Center
windows:
- window_name: dev window
  layout: tiled
  panes:
    - shell_command:
        - python3 ftp_server1.py
    - shell_command:
        - python3 ftp_server2.py
    - shell_command:
        - python3 conversation_engine.py
    - shell_command:
        - ./information.sh
    - shell_command:
        - bash